title: My Pseudo-Blog
author: Soupe
email: eric.campbell@student.riverspringscharter.org
description: > # this means to ignore newlines until "baseurl:"
  This site is just part of a Github Tutorial.
  
# social links
youtube_username: Song Playboy # DO NOT include the @ character, or else the build will fail!
github_username:  Dboi6339-Soupe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
